### ISSUE TITLE
ArgumentOutOfrangeException

### ISSUE THREAD

**Issue by Howiezhu** [LocalJoost/SlippyMapDemo#1]
Just downloaded slippyMapDemo. Is there some configuration that we need to set?

ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[ResourceSet].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
MapTile.ApplyElevationData (.ElevationResult elevationData) (at Assets/App/Scripts/MapTile.cs:88)
MapTile.ProcessElevationDataFromWeb () (at Assets/App/Scripts/MapTile.cs:80)
MapTile.OnUpdate () (at Assets/App/Scripts/MapTile.cs:61)
HoloToolkitExtensions.RemoteAssets.DynamicTextureDownloader.Update () (at Assets/HoloToolkitExtensions/Scripts/RemoteAssets/DynamicTextureDownloader.cs:23)

**Comment by LocalJoost** [comment]
I assume you downloaded the 3D branch. Did you get a map token?  
private string _mapToken = "your-map-token-here"; (MapTile, line 39)
Get one at the Bing Maps portal. 
http://dotnetbyexample.blogspot.nl/2017/08/creating-3d-topographical-map-in-your.html
